# Generated by Django 5.1 on 2024-09-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='time_date_created',
        ),
    ]
